version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0

env:
  - SCALAJS_VERSION=          ADOPTOPENJDK=8
  - SCALAJS_VERSION=0.6.31    ADOPTOPENJDK=8
  - SCALAJS_VERSION=1.0.0-RC1 ADOPTOPENJDK=8
  - SCALAJS_VERSION=          ADOPTOPENJDK=11
  - SCALAJS_VERSION=0.6.31    ADOPTOPENJDK=11
  - SCALAJS_VERSION=1.0.0-RC1 ADOPTOPENJDK=11

matrix:

  include:

    # run migration test
    - scala: 2.12.8
      env: TEST_SCALAFIX=true           ADOPTOPENJDK=11

    # run binary compatibility test
    - scala: 2.12.8
      env: TEST_BINARY_COMPAT=true      ADOPTOPENJDK=11

    # run scalafmt
    - scala: 2.12.8
      env: TEST_SCALAFMT=true           ADOPTOPENJDK=11

    # Scala Native includes
    - scala: 2.11.12
      env: SCALANATIVE_VERSION=0.3.9    ADOPTOPENJDK=8

    - scala: 2.11.12
      env: SCALANATIVE_VERSION=0.4.0-M2 ADOPTOPENJDK=8

    - scala: 2.11.12
      env: SCALANATIVE_VERSION=0.3.9    ADOPTOPENJDK=11

    - scala: 2.11.12
      env: SCALANATIVE_VERSION=0.4.0-M2 ADOPTOPENJDK=11

install:
  - git fetch --tags # get all tags for sbt-dynver

before_script:
  - admin/checkCLA.sh

script: sbt ci
