name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 25]
        scala: [2.11.x, 2.12.x, 2.13.x, 3.x]
        platform: [JVM, JS, Native]
        mode: [normal]
        exclude:
          - scala: 2.11.x
            platform: Native
        include:
          - java: 8
            scala: 2.12.x
            mode: testScalafix
            platform: JVM
          - java: 8
            scala: 2.12.x
            mode: testBinaryCompat
            platform: JVM
          - java: 8
            scala: 2.12.x
            mode: testScalafmt
            platform: JVM
          - java: 8
            scala: 2.12.x
            mode: headerCheck
            platform: JVM
    runs-on: ubuntu-latest
    env:
      CI_JDK: ${{matrix.java}}
      CI_SCALA_VERSION: ${{matrix.scala}}
      CI_MODE: ${{matrix.mode}}
      CI_PLATFORM: ${{matrix.platform}}
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{matrix.java}}
    - uses: sbt/setup-sbt@v1
    - name: ci
      run: sbt ci
